import turtle
def scene_5(t, width, height):
    # Restablecer posición y transformación
    t.setpos(0, 0)
    t.setheading(0)

    # Dibujar marco 1
    t.penup()
    t.setpos(-450, 335)
    t.pendown()
    t.color("black")
    for _ in range(2):
        t.forward(900)
        t.right(90)
        t.forward(500)
        t.right(90)

    # Dibujar marco 2
    t.penup()
    t.setpos(-450, 280)
    t.pendown()
    t.color("black")
    for _ in range(2):
        t.forward(900)
        t.right(90)
        t.forward(600)
        t.right(90)

    # Dibujar el oceano
    t.penup()
    t.setpos(-400, 250)
    t.pendown
    t.color("aquamarine4")
    t.begin_fill()
    for _ in range(2):
        t.forward(width)  # Ajustar el ancho del océano
        t.right(90)
        t.forward(height)  # Dejamos un espacio para la arena
        t.right(90)
    t.end_fill()


    # Dibujo de burbuja

    t.penup()
    t.goto(250, -50)
    t.pendown()
    t.color("aquamarine")
    t.shapesize(1)
    t.shape("circle")
    t.stamp()

    t.penup()
    t.goto(250, -50)
    t.pendown()
    t.color("azure")
    t.shapesize(0.2)
    t.shape("circle")
    t.stamp()

    # Dibujo de tortuga

    t.penup()
    t.goto(100, -50)
    t.pendown()
    t.color("ForestGreen")
    t.shapesize(5)
    t.setheading(90)
    t.shape("turtle")
    t.stamp()

    # Dibujo de tortuga

    t.penup()
    t.goto(100, -50)
    t.pendown()
    t.color("SpringGreen")
    t.shapesize(4.7)
    t.setheading(90)
    t.shape("turtle")
    t.stamp()

    # Dibujo de nombre de la tortuga

    t.penup()
    t.goto(100, 30)
    t.pendown()
    t.color("azure")
    t.write("Hasta pronto!", font=("Arial", 14, "bold"))


    #Dibujo de delfin
    def delfin():
        t.penup()
        t.goto(100, 120)
        t.pendown()
        t.color("LightBlue")
        t.shapesize(5, 1, 1)
        t.setheading(-45)
        t.shape("triangle")
        t.stamp()

        t.penup()
        t.goto(110, 100)
        t.pendown()
        t.color("LightBlue")
        t.shapesize(1, 3, 1)
        t.setheading(-65)
        t.shape("triangle")
        t.stamp()

        t.penup()
        t.goto(22, 110)
        t.pendown()
        t.color("LightBlue")
        t.shapesize(2, 4, 1)
        t.setheading(0)
        t.shape("square")
        t.stamp()

        t.penup()
        t.goto(40, 125)
        t.pendown()
        t.color("LightBlue")
        t.shapesize(6, 3, 1)
        t.setheading(260)
        t.shape("triangle")
        t.stamp()

        t.penup()
        t.goto(70, 122)
        t.pendown()
        t.color("LightBlue")
        t.shapesize(3.5, 2.8, 1)
        t.setheading(260)
        t.shape("triangle")
        t.stamp()

        t.penup()
        t.goto(-35, 120)
        t.pendown()
        t.color("LightBlue")
        t.shapesize(3.5, 2.9, 1)
        t.setheading(300)
        t.shape("triangle")
        t.stamp()

        t.goto(-10, 120)
        t.color("LightBlue")
        t.shapesize(2.5, 2.5, 1)
        t.setheading(90)
        t.shape("triangle")
        t.stamp()

        t.goto(-10, 155)
        t.color("LightBlue3")
        t.shapesize(2, 2, 1)
        t.setheading(90)
        t.shape("triangle")
        t.stamp()

        t.goto(20, 120)
        t.color("LightBlue3")
        t.shapesize(1, 2, 1)
        t.setheading(90)
        t.shape("triangle")
        t.stamp()

        t.goto(20, 100)
        t.color("LightBlue3")
        t.shapesize(1, 2, 1)
        t.setheading(270)
        t.shape("triangle")
        t.stamp()

        t.goto(-30, 120)
        t.color("black")
        t.shapesize(0.2)
        t.shape("circle")
        t.stamp()
        t.penup()

    delfin()

        # Dibujo de delfin
    def delfin_2():
        t.goto(-70, 160)
        t.color("LightBlue")
        t.shapesize(5, 1, 1)
        t.setheading(-45)
        t.shape("triangle")
        t.stamp()

        t.goto(-60, 140)
        t.color("LightBlue")
        t.shapesize(1, 3, 1)
        t.setheading(-65)
        t.shape("triangle")
        t.stamp()

        t.goto(-148, 150)
        t.color("LightBlue")
        t.shapesize(2, 4, 1)
        t.setheading(0)
        t.shape("square")
        t.stamp()

        t.goto(-130, 165)
        t.color("LightBlue")
        t.shapesize(6, 3, 1)
        t.setheading(260)
        t.shape("triangle")
        t.stamp()

        t.goto(-100, 162)
        t.color("LightBlue")
        t.shapesize(3.5, 2.8, 1)
        t.setheading(260)
        t.shape("triangle")
        t.stamp()

        t.goto(-205, 160)
        t.color("LightBlue")
        t.shapesize(3.5, 2.9, 1)
        t.setheading(300)
        t.shape("triangle")
        t.stamp()

        t.goto(-180, 160)
        t.color("LightBlue")
        t.shapesize(2.5, 2.5, 1)
        t.setheading(90)
        t.shape("triangle")
        t.stamp()

        t.goto(-180, 195)
        t.color("LightBlue3")
        t.shapesize(2, 2, 1)
        t.setheading(90)
        t.shape("triangle")
        t.stamp()

        t.goto(-150, 160)
        t.color("LightBlue3")
        t.shapesize(1, 2, 1)
        t.setheading(90)
        t.shape("triangle")
        t.stamp()

        t.goto(-150, 140)
        t.color("LightBlue3")
        t.shapesize(1, 2, 1)
        t.setheading(270)
        t.shape("triangle")
        t.stamp()

        t.goto(-200, 160)
        t.color("black")
        t.shapesize(0.2)
        t.shape("circle")
        t.stamp()

        t.goto(-140, 70)
        t.color("azure")
        t.write("Nos vemos!", font=("Arial", 14, "bold"))
        t.penup()
    delfin_2()

    #Dibujar algas

    t.penup()
    t.goto(-380, -100)
    t.pendown()
    t.color("green4")
    t.shapesize(0.5, 5, 1)
    t.shape("square")
    t.stamp()

    t.penup()
    t.goto(-350, -100)
    t.pendown()
    t.color("green3")
    t.shapesize(0.5, 4, 1)
    t.shape("square")
    t.stamp()

    t.goto(-320, -100)
    t.color("green2")
    t.shapesize(0.5, 5, 1)
    t.shape("square")
    t.stamp()

    t.goto(-310, -100)
    t.color("green3")
    t.shapesize(0.5, 3, 1)
    t.shape("square")
    t.stamp()

    t.goto(-280, -100)
    t.color("green")
    t.shapesize(0.5, 5, 1)
    t.shape("square")
    t.stamp()

    t.goto(-270, -100)
    t.color("green3")
    t.shapesize(0.5, 4.5, 1)
    t.shape("square")
    t.stamp()

    t.goto(-230, -100)
    t.color("green2")
    t.shapesize(0.5, 2, 1)
    t.shape("square")
    t.stamp()

    t.goto(-220, -100)
    t.color("green3")
    t.shapesize(0.5, 3.5, 1)
    t.shape("square")
    t.stamp()

    t.goto(-200, -100)
    t.color("green")
    t.shapesize(0.5, 5, 1)
    t.shape("square")
    t.stamp()

    t.goto(-180, -100)
    t.color("green3")
    t.shapesize(0.5, 5, 1)
    t.shape("square")
    t.stamp()

    t.goto(-160, -100)
    t.color("green")
    t.shapesize(0.5, 2.1, 1)
    t.shape("square")
    t.stamp()

    t.goto(-130, -100)
    t.color("green2")
    t.shapesize(0.5, 3.45, 1)
    t.shape("square")
    t.stamp()

    t.goto(-100, -100)
    t.color("green")
    t.shapesize(0.5, 5, 1)
    t.shape("square")
    t.stamp()

    t.goto(-90, -100)
    t.color("green2")
    t.shapesize(0.5, 4, 1)
    t.shape("square")
    t.stamp()

    t.goto(-70, -100)
    t.color("green3")
    t.shapesize(0.5, 3, 1)
    t.shape("square")
    t.stamp()

    t.goto(-60, -100)
    t.color("green2")
    t.shapesize(0.5, 2, 1)
    t.shape("square")
    t.stamp()

    t.goto(-40, -100)
    t.color("green3")
    t.shapesize(0.5, 1, 1)
    t.shape("square")
    t.stamp()

    t.goto(-20, -100)
    t.color("green2")
    t.shapesize(0.5, 4, 1)
    t.shape("square")
    t.stamp()

    t.goto(0, -100)
    t.color("green3")
    t.shapesize(0.5, 5, 1)
    t.shape("square")
    t.stamp()

    t.goto(0, -100)
    t.color("green4")
    t.shapesize(0.5, 5, 1)
    t.shape("square")
    t.stamp()

    t.goto(30, -100)
    t.color("green3")
    t.shapesize(0.5, 4, 1)
    t.shape("square")
    t.stamp()

    t.goto(60, -100)
    t.color("green2")
    t.shapesize(0.5, 5, 1)
    t.shape("square")
    t.stamp()

    t.goto(70, -100)
    t.color("green3")
    t.shapesize(0.5, 3, 1)
    t.shape("square")
    t.stamp()

    t.goto(100, -100)
    t.color("green")
    t.shapesize(0.5, 5, 1)
    t.shape("square")
    t.stamp()

    t.goto(110, -100)
    t.color("green3")
    t.shapesize(0.5, 4.5, 1)
    t.shape("square")
    t.stamp()

    t.goto(150, -100)
    t.color("green2")
    t.shapesize(0.5, 2, 1)
    t.shape("square")
    t.stamp()

    t.goto(160, -100)
    t.color("green3")
    t.shapesize(0.5, 3.5, 1)
    t.shape("square")
    t.stamp()

    t.goto(180, -100)
    t.color("green")
    t.shapesize(0.5, 5, 1)
    t.shape("square")
    t.stamp()

    t.goto(200, -100)
    t.color("green3")
    t.shapesize(0.5, 5, 1)
    t.shape("square")
    t.stamp()

    t.goto(220, -100)
    t.color("green")
    t.shapesize(0.5, 2.1, 1)
    t.shape("square")
    t.stamp()

    t.goto(250, -100)
    t.color("green2")
    t.shapesize(0.5, 3.45, 1)
    t.shape("square")
    t.stamp()

    t.goto(280, -100)
    t.color("green")
    t.shapesize(0.5, 5, 1)
    t.shape("square")
    t.stamp()

    t.goto(290, -100)
    t.color("green2")
    t.shapesize(0.5, 4, 1)
    t.shape("square")
    t.stamp()

    t.goto(310, -100)
    t.color("green3")
    t.shapesize(0.5, 3, 1)
    t.shape("square")
    t.stamp()

    t.goto(320, -100)
    t.color("green2")
    t.shapesize(0.5, 2, 1)
    t.shape("square")
    t.stamp()

    t.goto(340, -100)
    t.color("green3")
    t.shapesize(0.5, 1, 1)
    t.shape("square")
    t.stamp()

    t.goto(360, -100)
    t.color("green2")
    t.shapesize(0.5, 4, 1)
    t.shape("square")
    t.stamp()

    t.penup()
    t.goto(380, -100)
    t.pendown()
    t.color("green3")
    t.shapesize(0.5, 5, 1)
    t.shape("square")
    t.stamp()
    t.penup()
    